#       makefile for C# program CSC543FinalProject
#       final project for CSC 543,
#       Spring 2021, Bob Elward

clean:	
		dotnet clean ./CSC543FinalProject.csproj

build:	
		dotnet build ./CSC543FinalProject.csproj
		
run:	
		dotnet run ./CSC543FinalProject.csproj
		